### ISSUE TITLE
users should select onedrive as a source here rather than a channel on the left bar

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#409]
![image](https://user-images.githubusercontent.com/3675043/120337004-ec5d9f00-c2c0-11eb-9815-f313c84ecaad.png)

**Comment by bluenevus** [comment]
also the formatting is off and you really can't see the buttons

**Comment by bluenevus** [comment]
can we also provide a drag and drop box here for the file?

**Comment by bluenevus** [comment]
it really needs to be just another data set within a channel 

![image](https://user-images.githubusercontent.com/3675043/120644322-31124300-c445-11eb-8342-fcd5c3645f31.png)

**Comment by bluenevus** [comment]
It should come from the root of My Files vs documents folders as the root My Files includes all the document folders including Documents

**Comment by bluenevus** [comment]
ideally its a seamless experience like so https://app.diagrams.net/ but data sources just show like any data source in the data set in the channel

**Comment by bluenevus** [comment]
just having the abiltiy to see it and download it then upload sort of defeats the purpose of onedrive integration as its far faster for me to just use onedrive.  the integration was intended to be just another data source in the add data workflow like url, like upload

**Comment by bluenevus** [comment]
also this took nearly a minute to show 
![image](https://user-images.githubusercontent.com/3675043/120800551-122bb380-c50e-11eb-9903-e03ac22a5a7c.png)

**Comment by bluenevus** [comment]
honestly  I hate to say it but as it stands, the one drive feature is completely unusable as 1.  its really slow to load.  If you're lucky its one minute.  its more likely 3 minutes.  Next, it only gives me the ability to download the file I already have in my one drive on my computer which I can upload.  I really don't need to download.  I really need the integration into the data sources so it works just like this https://app.diagrams.net/

**Comment by b-solution** [comment]
<img width="574" alt="Screenshot 2021-06-09 at 4 29 29 PM" src="https://user-images.githubusercontent.com/5988861/121348242-89fc4280-c941-11eb-84bf-db66db4148cd.png">


<img width="1168" alt="Screenshot 2021-06-09 at 4 31 40 PM" src="https://user-images.githubusercontent.com/5988861/121348424-c92a9380-c941-11eb-9893-d1efc61da477.png">

**Comment by b-solution** [comment]
@bluenevus I have implemented the basic functionality of one drive file picker you had asked for. Please test it and provide me your feedback. I'll add drag and drop functionality in #410

**Comment by bluenevus** [comment]
this is definitely where we want to go.  the onedrive button doesn't do anything though 
![image](https://user-images.githubusercontent.com/3675043/121386998-51943e80-c918-11eb-869d-4aa79d6a4f79.png)

**Comment by b-solution** [comment]
Can you please precompile assets, restart server and try again. It's working for me. 
It will open one drive in new window and display all files and folders like in above screenshot.

**Comment by bluenevus** [comment]
I did precompile and nothing happened so I

 rake assets:clobber RAILS_ENV=production
then 
rake assets:precompile RAILS_ENV=production

just sits there...hung after 15 minutes.  It won't precompile

**Comment by bluenevus** [comment]
@b-solution  clobbered the assets in production env, precompiled again in production env, one drive still not opening,  tried in private browser for chrome and firefox.

**Comment by bluenevus** [comment]
and nginx owns the directory for permission

**Comment by b-solution** [comment]
<img width="1308" alt="Screenshot 2021-06-10 at 3 39 35 PM" src="https://user-images.githubusercontent.com/5988861/121511671-533a3100-ca02-11eb-8efe-a44cdbc552a0.png">

Goto your register application on Azur, under Authentication tab add a web platform and Redirect URI like in the picture '{baseurl}/welcome/onedriveredirect'. and save it.

**Comment by b-solution** [comment]
<img width="1342" alt="Screenshot 2021-06-10 at 3 42 17 PM" src="https://user-images.githubusercontent.com/5988861/121512882-a52f8680-ca03-11eb-825d-2f2011a1abed.png">

after adding redirect url scroll down on same page and check following boxes like in screenshot and save it.

Hopefully after successful configuration of redirect url and implicit flow check boxes. it will work.

**Comment by bluenevus** [comment]
onedrive is coming up now however the url changed

{ENV['CALLBACK_URL']}/auth/microsoft_graph_auth/callback", ENV['AZURE_SCOPES'])

this  no longer works  https://YourliveSiteDomain/auth/microsoft_graph_auth/callback

this at the end ENV['AZURE_SCOPES']) results in this error message and I'm not sure how to formultate the callback url

![image](https://user-images.githubusercontent.com/3675043/121524747-9f1ab500-c9c5-11eb-987e-17ab9774fcd4.png)

the two checkboxes are checked as you metnion
